{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ix-csi.fullname" . }}-controller-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ix-csi.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    - name: prov-metrics
      port: 9801
      targetPort: prov-metrics
      protocol: TCP
    - name: attach-metrics
      port: 9802
      targetPort: attach-metrics
      protocol: TCP
    - name: snap-metrics
      port: 9803
      targetPort: snap-metrics
      protocol: TCP
    - name: resize-metrics
      port: 9804
      targetPort: resize-metrics
      protocol: TCP
  selector:
    {{- include "ix-csi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ix-csi.fullname" . }}-node-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ix-csi.labels" . | nindent 4 }}
    app.kubernetes.io/component: node
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "ix-csi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node
{{- end }}
