{{- if not .Values.secret.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ix-csi.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ix-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
  TRUENAS_API_KEY: {{ .Values.secret.apiKey | quote }}
{{- end }}
