apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "truenas-csi.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "truenas-csi.labels" . | nindent 4 }}
data:
  TRUENAS_URL: {{ .Values.config.truenasURL | quote }}
  TRUENAS_INSECURE_SKIP_VERIFY: {{ .Values.config.truenasInsecure | quote }}
  TRUENAS_DEFAULT_POOL: {{ .Values.config.defaultPool | quote }}
  {{- if .Values.config.nfsServer }}
  TRUENAS_NFS_SERVER: {{ .Values.config.nfsServer | quote }}
  {{- end }}
  {{- if .Values.config.iscsiPortal }}
  TRUENAS_ISCSI_PORTAL: {{ .Values.config.iscsiPortal | quote }}
  {{- end }}
  {{- if .Values.config.nvmeofPortal }}
  TRUENAS_NVMEOF_PORTAL: {{ .Values.config.nvmeofPortal | quote }}
  {{- end }}
  {{- if .Values.config.iscsiIQNBase }}
  TRUENAS_ISCSI_IQN_BASE: {{ .Values.config.iscsiIQNBase | quote }}
  {{- end }}
  {{- if .Values.config.detachedSnapshotsDatasetParentName }}
  TRUENAS_DETACHED_SNAPSHOTS_DATASET_PARENT: {{ .Values.config.detachedSnapshotsDatasetParentName | quote }}
  {{- end }}
