apiVersion: v2
name: ix-csi
description: Helm chart for deploying the ix-csi driver
home: https://github.com/ishioni/ix-csi
type: application
# version + appVersion are overridden at package time from the release tag.
version: 0.0.0
appVersion: "0.0.0"
kubeVersion: ">=1.26.0-0"
keywords:
  - csi
  - storage
  - truenas
  - zfs
sources:
  - https://github.com/ishioni/ix-csi
maintainers:
  - name: ix-csi
